artifacts_roots: artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_file: datas/datas.csv
  save_file : cryptos.csv

data_validation:
  root_dir : artifacts/data_validation
  data_file : artifacts/data_ingestion/cryptos.csv
  STATUS_FILE : artifacts/data_validation/status.txt

data_transformation:
  root_dir : artifacts/data_transformation
  data_file : artifacts/data_ingestion/cryptos.csv


model_trainer:
  root_dir : artifacts/model_trainer
  x_train_data_path: artifacts/data_transformation/X_train
  y_train_data_path: artifacts/data_transformation/y_train
  model_file: trained_model



model_evaluation:
  root_dir : artifacts/model_evaluation
  x_test_data_path: artifacts/data_transformation/X_test
  y_test_data_path: artifacts/data_transformation/y_test
  model_file: artifacts/model_trainer/trained_model
  metric_file_name: artifacts/model_evaluation/metrics.json

